FROM scratch

ADD sbin/apk.static /sbin/
ADD etc/apk/repositories /etc/apk/
RUN [ "/sbin/apk.static", "--allow-untrusted", "-U", \
      "add", "--initdb", \
      "alpine-keys" ]

RUN ["/sbin/apk.static", "add", "--update", "alpine-base", "xvfb", "wine", "wget", "py-pip"]
ADD winetricks.sh /
RUN chmod +x winetricks.sh && mv winetricks.sh /usr/bin/winetricks

ENV WINEARCH win32
ENV DISPLAY :0
ENV REGION eu-west-1

COPY pbdm /

RUN \
    echo "**** install Python ****" && \
    apk add --no-cache python3 && \
    if [ ! -e /usr/bin/python ]; then ln -sf python3 /usr/bin/python ; fi && \
    pip3 install --upgrade pip && \
    pip3 install awscli && \
    rm /var/cache/apk/* && \
	mkdir -p /aws && \
	apk -Uuv add groff less python3 py-pip 

RUN \
	pip3 install boto3 

RUN \	
    echo "**** install Build-Base ****" && \
	apk add build-base && \
	apk add python3-dev && \
	apk add libffi && \
	apk add libffi-dev && \
	apk add openssl-dev && \
    apk add awscli

RUN \
    apk add --update python3 python3-dev py-pip build-base && \
	apk --purge -v del py-pip 
	
RUN \
    echo "         **** Config Wine ****" && \
    echo "↓↓↓ Don't worry about these errors ↓↓↓" && \
    winecfg && \
    echo "^^^ Don't worry about these errors ^^^"

COPY run.sh /
ENTRYPOINT ["/bin/sh"]
CMD ["run.sh"]
