server {
    listen 443 ssl;
    server_name casas.my.domain.;
    server_tokens off;
    client_max_body_size 20m;

    ssl_certificate             /etc/ssl/private/cert_bundle.pem;
    ssl_certificate_key         /etc/ssl/private/privateKey.pem;

    location / {
        proxy_pass http://casaswebapp:8080;
        proxy_set_header Host $host;
        proxy_set_header X-Real-IP $remote_addr;
        proxy_set_header X-Forwarded-Host $host;
        proxy_set_header X-Forwarded-For $proxy_add_x_forwarded_for;
        proxy_set_header X-Forwarded-Proto $scheme;
        proxy_set_header X-NginX-Proxy true;
        proxy_redirect off;
        proxy_connect_timeout       300;
        proxy_send_timeout          300;
        proxy_read_timeout          300;
        send_timeout                300;
    }

    location /media/{
        alias /opt/media/; # media files directory full path will be /opt/media
    }
}
