app: dev-pbdm-backend-app
service: dev-pbdm-backend-api

plugins:
  - serverless-pseudo-parameters
  - serverless-reqvalidator-plugin


provider:
  name: aws
  runtime: python3.9
  region: ${opt:region, 'eu-west-1'}
  stage: ${opt:stage, 'dev'}
  project: mgd-ict-platform
  endpointType: REGIONAL
  stackTags:
    Name: mgd-ict-platform-backend
    Environment: ${self:provider.stage}
    Role: pbdm-wf

custom:
  env:  ${self:provider.stage}
  BUCKET_NAME: dev-pbdm-workflow
  workflow_table: dev-pbdm-workflow
  clusterName: ${self:provider.stage}-${self:provider.project}-pbdm-wf-cluster
  #fargateLambdaName: ${self:provider.stage}-${self:provider.project}--pbdm-wf-worker-fargate
  StepFunctionArn: "arn:aws:states:${self:provider.region}:#{AWS::AccountId}:stateMachine:${self:provider.stage}-${self:provider.project}-pbdm-sf"
  StepFunctionExecutionArn: "arn:aws:states:${self:provider.region}:#{AWS::AccountId}:execution:${self:provider.stage}-${self:provider.project}-pbdm-sf:"
  cognito_arn: "arn:aws:cognito-idp:eu-west-1:284176251738:userpool/eu-west-1_owfEtSFcp"

# LAMBDAS
functions: ${file(resources/functions.yml):functions}

resources:
  # IAM-ROLE
  - ${file(resources/iam-roles.yml)}
  - ${file(resources/ec2.yml)}