Resources:
  PbdmTable:
    Type: AWS::DynamoDB::Table
    Properties:
      TableName: "${self:custom.dynamodbtable}"
      AttributeDefinitions:
        - 
          AttributeName: !Ref HashKeyElementName
          AttributeType: !Ref HashKeyElementType
      KeySchema:
        - 
          AttributeName: id
          KeyType: HASH
      ProvisionedThroughput:
        ReadCapacityUnits: 5
        WriteCapacityUnits: 5 