Resources:
  cluster:
    Type: AWS::ECS::Cluster
    Properties:
      ClusterName: ${self:provider.stage}-pbdm-wf-cluster
  
  LogGroup:
    Type: AWS::Logs::LogGroup
    Properties:
      LogGroupName: "${self:provider.stage}-pbdm-wf-log-group"
      RetentionInDays: 30 

  taskDefinition:
    Type: AWS::ECS::TaskDefinition
    Properties: 
      ContainerDefinitions: 
        - Name: "${self:provider.stage}-pbdm-wf-container"
          Cpu: 1
          Essential: true
          MountPoints:
            - ContainerPath: "/filesystem"
              SourceVolume: data
          Image: "#{AWS::AccountId}.dkr.ecr.${self:provider.region}.amazonaws.com/${self:provider.stage}-pbdm-wf-worker-image:latest"
          LogConfiguration:
            LogDriver: awslogs
            Options:
              awslogs-group: "${self:provider.stage}-pbdm-wf-log-group"
              awslogs-region: ${self:provider.region}
              awslogs-stream-prefix: "${file(serverless.yml):custom.task_definition}"
      Cpu: "2048"
      ExecutionRoleArn: "arn:aws:iam::#{AWS::AccountId}:role/${file(resources/iam-roles.yml):Resources.ecsTaskExecutionRole.Properties.RoleName}"
      TaskRoleArn: "arn:aws:iam::#{AWS::AccountId}:role/${file(resources/iam-roles.yml):Resources.ecsTaskExecutionRole.Properties.RoleName}"
      Family: "${file(serverless.yml):custom.task_definition}"
      Memory: "8GB"
      NetworkMode: "awsvpc"
      RequiresCompatibilities: 
        - FARGATE
      Volumes:
        - Name: data
          EfsVolumeConfiguration:
            FileSystemId: fs-07dbdf698dfaa165c
  ecr:
    Type: AWS::ECR::Repository
    Properties: 
      RepositoryName: ${self:provider.stage}-pbdm-wf-worker-image
  
  SecurityGroupEFS:
    Type: AWS::EC2::SecurityGroup
    Properties: 
      GroupDescription: "EFS security group"
      GroupName: ${self:provider.stage}-pbdm-wf-efs-sg
      SecurityGroupIngress: 
        - IpProtocol: tcp
          FromPort: 2049
          ToPort: 2049
          SourceSecurityGroupId: 
            Ref: SecurityGroup
      VpcId: 
        Ref: VPC
      Tags: 
       - Key: Name
         Value: ${self:provider.stage}-pbdm-wf-efs-sg

  FileSystem:
    Type: AWS::EFS::FileSystem
    Properties: 
      FileSystemTags:
      - Key: Name
        Value: ${self:provider.stage}-pbdm-wf-efs

  MountTarget:
    Type: AWS::EFS::MountTarget
    Properties:
      FileSystemId: 
        Ref: FileSystem
      SecurityGroups:
        [Ref: SecurityGroupEFS]
      SubnetId:
        Ref: Subnet
