Resources:

    stepfunctionrole:
        Type: AWS::IAM::Role
        Properties:
            RoleName: ${self:provider.stage}-pbdm-StepFunctionRole
            AssumeRolePolicyDocument:
                Version: '2012-10-17' 
                Statement:
                    -   Effect: Allow
                        Principal:
                            Service:
                                - lambda.amazonaws.com
                                - states.amazonaws.com
                        Action: sts:AssumeRole
            ManagedPolicyArns:
                -   arn:aws:iam::aws:policy/service-role/AmazonECSTaskExecutionRolePolicy
            Policies:
                -   PolicyName: ${self:provider.stage}-pbdm-StepFunctionPolicy
                    PolicyDocument:
                        Version: '2012-10-17'
                        Statement:
                            -   Effect: Allow
                                Action:
                                    - "ecs:RunTask"
                                Resource: "arn:aws:ecs:${file(serverless.yml):provider.region}:#{AWS::AccountId}:cluster/${file(resources/ecs.yml):Resources.cluster.Properties.ClusterName}"        
                            -   Effect: Allow
                                Action:
                                    - "ecs:RunTask"
                                Resource: "arn:aws:ecs:${file(serverless.yml):provider.region}:#{AWS::AccountId}:task-definition/${file(serverless.yml):custom.task_definition}:*"
                            -   Effect: Allow
                                Action:
                                    - events:PutTargets
                                    - events:PutRule
                                    - events:DescribeRule
                                Resource:  arn:aws:events:${file(serverless.yml):provider.region}:#{AWS::AccountId}:rule/StepFunctionsGetEventsForECSTaskRule
                            -   Effect: Allow
                                Action:
                                    - iam:PassRole
                                Resource: "arn:aws:iam::#{AWS::AccountId}:role/${self:provider.stage}-pbdm-ecsTaskExecutionRole"
    ecsTaskExecutionRole:
        Type: AWS::IAM::Role
        Properties:
            RoleName: "${self:provider.stage}-pbdm-ecsTaskExecutionRole"
            AssumeRolePolicyDocument:
                Version: '2012-10-17'
                Statement:
                    -   Effect: Allow
                        Principal:
                            Service:
                                - lambda.amazonaws.com
                                - ecs-tasks.amazonaws.com
                                - ec2.amazonaws.com
                        Action: sts:AssumeRole
            ManagedPolicyArns:
                -   arn:aws:iam::aws:policy/service-role/AmazonECSTaskExecutionRolePolicy
            Policies:
                -   PolicyName: ${self:provider.stage}-pbdm-ecsTaskExecutionPolicy
                    PolicyDocument:
                        Version: '2012-10-17'
                        Statement:
                            -   Effect: Allow
                                Action:
                                    - "s3:PutObject"
                                    - "s3:ListBucket"
                                    - "s3:PutObjectAcl"
                                    - "s3:GetObject"
                                Resource:
                                    - "arn:aws:s3:::data.med-gold.eu"
                                    - "arn:aws:s3:::*/*"

                            -   Effect: Allow
                                Action:
                                    - "logs:CreateLogGroup"
                                    - "logs:CreateLogStream"
                                    - "logs:PutLogEvents"
                                Resource: "*"
