 stepfunctionrole:
    Type: 'AWS::IAM::Role'
    Properties:
      RoleName: dev-pbdm-StepFunctionRole
      AssumeRolePolicyDocument:
        Version: 2012-10-17
        Statement:
          - Effect: Allow
            Principal:
              Service:
                - lambda.amazonaws.com
                - states.amazonaws.com
            Action: 'sts:AssumeRole'
      ManagedPolicyArns:
        - 'arn:aws:iam::aws:policy/service-role/AmazonECSTaskExecutionRolePolicy'
      Policies:
        - PolicyName: dev-pbdm-StepFunctionPolicy
          PolicyDocument:
            Version: 2012-10-17
            Statement:
              - Effect: Allow
                Action:
                  - 'ecs:RunTask'
                Resource: !Sub >-
                  arn:aws:ecs:eu-west-1:${AWS::AccountId}:cluster/dev-pbdm-wf-cluster
              - Effect: Allow
                Action:
                  - 'ecs:RunTask'
                Resource: !Sub >-
                  arn:aws:ecs:eu-west-1:${AWS::AccountId}:task-definition/dev-pbdm-task-definition:*
              - Effect: Allow
                Action:
                  - 'events:PutTargets'
                  - 'events:PutRule'
                  - 'events:DescribeRule'
                Resource: !Sub >-
                  arn:aws:events:eu-west-1:${AWS::AccountId}:rule/StepFunctionsGetEventsForECSTaskRule
              - Effect: Allow
                Action:
                  - 'iam:PassRole'
                Resource: !Sub >-
                  arn:aws:iam::${AWS::AccountId}:role/dev-pbdm-ecsTaskExecutionRole